### ISSUE TITLE
What is the meaning of '$'

### ISSUE THREAD

**Issue by swork1** [ThomasMertes/seed7#14]
What is the meaning of needing a '$' in each sd7 file? For example 
```
$ include "seed7_05.s7i";
  include "rational.s7i";
```

As without the '$' it will not compile. The only explanation I could find was in the[Syntax](https://seed7.sourceforge.net/manual/syntax.htm) part of the manual stating
> The $ is used to introduce all hard coded statements.

Is there a better explanation somewhere that I'm missing?

**Comment by ThomasMertes** [comment]
I just improved the (already existing) FAQ answer regarding:
[Why are there dollar signs in some places?](https://seed7.sourceforge.net/faq.htm#dollar_signs)
If you have more questions don't hesitate to ask.

**Comment by swork1** [comment]
Thanks makes sense, must have missed that faq
