### ISSUE TITLE
How to report a security problem?

### ISSUE THREAD

**Issue by DemiMarie** [ThomasMertes/seed7#25]
How should I report a security problem in seed7?

**Comment by celtic-coder** [comment]
Hi Demi Marie (@DemiMarie), 

Use the following and put "Seed7" in the Subject line:

~~~
 thomas.mertes -AT- gmx.at
~~~

Kind Regards,
Liam

**Comment by ThomasMertes** [comment]
I am awaiting your email.

**Comment by DemiMarie** [comment]
Sent @ThomasMertes.

**Comment by ThomasMertes** [comment]
This is discussed in emails.
