### ISSUE TITLE
Typo in SourceForge Release date and URL

### ISSUE THREAD

**Issue by celtic-coder** [ThomasMertes/seed7#29]
Hi Thomas (@ThomasMertes),

Both the [News](https://sourceforge.net/p/seed7/news/) summary page on SourceForge and the detailed page for the March 1st 2024 release (https://sourceforge.net/p/seed7/news/2024/03/new-seed7-release-2023-03-01/) shows:

~~~
New Seed7 Release 2023-03-01
~~~

Both the heading and the URL reflect the date given.

Kind Regards,
Liam

**Comment by ThomasMertes** [comment]
Thank you for the hint. I just fixed it.

Kind Regards,
Thomas
