### ISSUE TITLE
ctest Compiler Error (General Settings) in Windows 10 install

### ISSUE THREAD

**Issue by celtic-coder** [ThomasMertes/seed7#31]
[comment]: # (https://github.com/ThomasMertes/seed7/issues/31)

Hi Thomas (@ThomasMertes),

Yesterday, I installed Seed7 on a new Windows 10 PC. I used the downloaded `seed7_05_20231217_win.exe` to install Version 2024-06-30 into the "C:\Seed7" folder.

During the installation, the following error occurred in the _**General Settings**_ portion:

~~~
Numeric sizes: ......................... determined
General settings: ..................................................
 *** Cannot define os_rename_orig.

Compiler errors:
ctest80.c: In function 'main':
ctest80.c:4:5: error: implicit declaration of function '_wrename'; did you mean 'rename'? [-Wimplicit-function-declaration]
    4 |     _wrename(L"testfile", L"newname") == 0);
      |     ^~~~~~~~
      |     rename

............................................. determined
Numeric properties: .............................................................................................. determined
~~~

The installation continued without any further error and "chk_all" had no problems.

One thing I noticed in the "**C:\Seed7\src\version.h**" file that might have some bearing on this issue is that C_COMPILER_VERSION had been changed from when I previously did the installation of Version 2024-03-01 on my other Windows 10 machine.

The valued had changed from `gcc (GCC) 13.2.0` to `gcc (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders, r3) 14.1.0`.

I don't know if the compiler version might be at fault, but I wanted you to be aware of this in case it had a bearing on the problem.

Kind Regards,
Liam

**Comment by ThomasMertes** [comment]
Hi Liam,

In the past Seed7 defined `os_remove` under Windows with:
#define os_rename _wrename
Usually `_wrename()` is defined in Windows. I am wondering that it is missing on your computer.

Newer versions of Seed7 do not use `_wrename()` and define `os_remove` under Windows with:
#define os_rename winRename
The function `winRename()` is defined in `cmd_win.c` and is based on the Win32 function `MoveFileExW()`.

Luckily the macro `os_rename_orig` is not used in other *.c and *.h files.

The commit ([Remove test of _wrename() and definition of os_rename_orig](https://github.com/ThomasMertes/seed7/commit/79097f22e4a3ebdc6940817e0b619c250357533b)) removes the definition of `os_rename_orig` and the corresponding test program in `chkccomp.c`.

The newest version from GitHub should fix this issue.

Kind Regards
Thomas

**Comment by celtic-coder** [comment]
[comment]: # (https://github.com/ThomasMertes/seed7/issues/31)

Hi Thomas (@ThomasMertes),

Thanks for making that change! The `_wrename` is not on my newer Windows 10 machine. However, the following files are on my older PC:

~~~
C:\Program Files (x86)\Windows Kits\10\Source\10.0.10240.0\ucrt\filesystem\wrename.cpp
C:\Program Files (x86)\Windows Kits\10\Source\10.0.18362.0\ucrt\filesystem\wrename.cpp
~~~

These files are from 2015 and 2018, but there are no executable versions that I can see. So, I guess that this only applies to possibly older versions of Windows. 

I did a quick check online, but it seems that the only problem occurred if the target of the file being renamed already existed and this did not seem to raise an error. However, I don't think that this would have occurred during the installation process.

Thanks again for making the change. I'll have a look at the updated version and if there is any problem, I'll respond in this issue.

Kind Regards,
Liam
